import os
import json
import numpy as np
from tensorflow import keras

OUTPUT_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "outputs")


def extract_weights(model_dir):
    autoencoder = keras.models.load_model(os.path.join(model_dir, "autoencoder.keras"))

    with open(os.path.join(model_dir, "results.json")) as f:
        results = json.load(f)

    encoder = autoencoder.get_layer("encoder")
    decoder = autoencoder.get_layer("decoder")

    encoder_layers = []
    for layer in encoder.layers:
        if hasattr(layer, "get_weights") and layer.get_weights():
            w, b = layer.get_weights()
            encoder_layers.append({"weights": w, "bias": b})

    decoder_layers = []
    for layer in decoder.layers:
        if hasattr(layer, "get_weights") and layer.get_weights():
            w, b = layer.get_weights()
            decoder_layers.append({"weights": w, "bias": b})

    scaler_mean = np.load(os.path.join(model_dir, "scaler_mean.npy"))
    scaler_scale = np.load(os.path.join(model_dir, "scaler_scale.npy"))

    return {
        "encoder_layers": encoder_layers,
        "decoder_layers": decoder_layers,
        "scaler_mean": scaler_mean,
        "scaler_scale": scaler_scale,
        "threshold": results["threshold"],
        "input_dim": results["input_dim"],
        "hidden_dims": results["hidden_dims"],
        "feature_names": results["feature_names"],
    }


def _format_array_1d(arr, name, dtype="float"):
    values = ", ".join(f"{v:.8f}f" for v in arr)
    return f"const {dtype} {name}[{len(arr)}] = {{{values}}};"


def _format_array_2d(arr, name, dtype="float"):
    rows, cols = arr.shape
    lines = [f"const {dtype} {name}[{rows}][{cols}] = {{"]
    for i in range(rows):
        values = ", ".join(f"{v:.8f}f" for v in arr[i])
        comma = "," if i < rows - 1 else ""
        lines.append(f"  {{{values}}}{comma}")
    lines.append("};")
    return "\n".join(lines)


def generate_header(model_info, config_name="esp32_deploy"):
    input_dim = model_info["input_dim"]
    hidden_dims = model_info["hidden_dims"]
    threshold = model_info["threshold"]

    lines = []
    lines.append("// Auto-generated by ML pipeline - DO NOT EDIT")
    lines.append(f"// Model: {config_name}")
    lines.append(f"// Architecture: {input_dim} -> {' -> '.join(map(str, hidden_dims))} -> {input_dim}")
    lines.append(f"// Threshold: {threshold}")
    lines.append("")
    lines.append("#ifndef MODEL_WEIGHTS_H")
    lines.append("#define MODEL_WEIGHTS_H")
    lines.append("")
    lines.append(f"#define MODEL_INPUT_DIM {input_dim}")
    lines.append(f"#define MODEL_N_ENCODER_LAYERS {len(model_info['encoder_layers'])}")
    lines.append(f"#define MODEL_N_DECODER_LAYERS {len(model_info['decoder_layers'])}")
    lines.append(f"#define MODEL_THRESHOLD {threshold:.8f}f")
    lines.append("")

    dims = [input_dim] + hidden_dims
    for i, layer in enumerate(model_info["encoder_layers"]):
        lines.append(f"// Encoder layer {i}: {dims[i]} -> {dims[i+1]}")
        lines.append(_format_array_2d(layer["weights"], f"encoder_w{i}"))
        lines.append(_format_array_1d(layer["bias"], f"encoder_b{i}"))
        lines.append("")

    dims_dec = hidden_dims[::-1] + [input_dim]
    for i, layer in enumerate(model_info["decoder_layers"]):
        in_d = hidden_dims[-1] if i == 0 else dims_dec[i]
        out_d = dims_dec[i + 1] if i + 1 < len(dims_dec) else input_dim
        lines.append(f"// Decoder layer {i}: {in_d} -> {out_d}")
        lines.append(_format_array_2d(layer["weights"], f"decoder_w{i}"))
        lines.append(_format_array_1d(layer["bias"], f"decoder_b{i}"))
        lines.append("")

    lines.append("// Scaler parameters (StandardScaler)")
    lines.append(_format_array_1d(model_info["scaler_mean"], "scaler_mean"))
    lines.append(_format_array_1d(model_info["scaler_scale"], "scaler_scale"))
    lines.append("")

    lines.append("// Feature names (for reference)")
    for i, name in enumerate(model_info["feature_names"]):
        lines.append(f"// Feature {i}: {name}")

    lines.append("")
    lines.append("#endif // MODEL_WEIGHTS_H")
    lines.append("")

    return "\n".join(lines)


def export_for_esp32(config_name="esp32_deploy"):
    print(f"\n{'='*60}")
    print(f"Exporting model '{config_name}' for ESP32")
    print(f"{'='*60}")

    model_dir = os.path.join(OUTPUT_DIR, "models", config_name)
    if not os.path.exists(model_dir):
        print(f"  ERROR: Model directory not found: {model_dir}")
        return None

    model_info = extract_weights(model_dir)

    header = generate_header(model_info, config_name)

    header_path = os.path.join(OUTPUT_DIR, "models", "model_weights.h")
    with open(header_path, "w") as f:
        f.write(header)

    n_params = 0
    for layer in model_info["encoder_layers"]:
        n_params += layer["weights"].size + layer["bias"].size
    for layer in model_info["decoder_layers"]:
        n_params += layer["weights"].size + layer["bias"].size
    n_params += len(model_info["scaler_mean"]) + len(model_info["scaler_scale"])

    memory_bytes = n_params * 4  # float32

    print(f"  Input dimension: {model_info['input_dim']}")
    print(f"  Architecture: {model_info['input_dim']} -> {' -> '.join(map(str, model_info['hidden_dims']))} -> {model_info['input_dim']}")
    print(f"  Total parameters: {n_params}")
    print(f"  Memory footprint: {memory_bytes} bytes ({memory_bytes/1024:.1f} KB)")
    print(f"  Threshold: {model_info['threshold']:.6f}")
    print(f"  Header saved to: {header_path}")

    return header_path


if __name__ == "__main__":
    export_for_esp32()
